#!/bin/zsh
[[ ! -p /dev/stdin ]] && exit 0
if [[ "$1" == "-all" ]] || [[ "$1" == "-c" ]]; then
	set -x
	if [[ "$1" == "-all" ]]; then
		c=1
	else
		c=${2:-1}
		[[ -n "$2" ]] && shift
	fi
	shift
	c=$((30+$c))
	while read line; do
		echo "\033[${c}m${line}\033[0m"
	done
	set +x
else
	awk '
	BEGIN{IGNORECASE=1}
	function color(c,s) {
		printf("\033[%dm%s\033[0m\n",30+c,s)
	}
	/\.php/ {color(2,$0);next}
	/error/ {color(1,$0);next}
	/success/ {color(2,$0);next}
	/warning/ {color(3,$0);next}
	/INFO/ {color(4,$0);next}
	/DBG/ {color(5,$0);next}
	{print}
	' $1
fi
