#!/bin/zsh

#echo 2400000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
#echo 2400000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
#echo 2400000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
#echo 2400000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
#if [[ $1 == ]]
#[[ -o interactive ]] && chooser -v opt performance - Run the CPU at the maximum frequency.
#powersave 	Run the CPU at the minimum frequency.
#userspace 	Run the CPU at user specified frequencies.
#ondemand 	Scales the frequency dynamically according to current load. Jumps to the highest frequency and then possibly back off as the idle time increases.
#conservative 	Scales the frequency dynamically according to current load. Scales the frequency more gradually than ondemand.
#schedutil
#for f in /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor; do
	#echo $governor | sudo tee $f
#done
sudo cpupower -c 0,1 frequency-set -g conservative
sudo cpupower -c 2,3 frequency-set -g powersave
# temperature is in m°C
/usr/bin/dbus-send --system --dest=org.freedesktop.thermald /org/freedesktop/thermald org.freedesktop.thermald.SetUserMaxTemperature string:cpu uint32:77000
/usr/bin/dbus-send --system --dest=org.freedesktop.thermald /org/freedesktop/thermald org.freedesktop.thermald.SetCurrentPreference string:"ENERGY_CONSERVE"
# watch grep \"cpu MHz\" /proc/cpuinfo
# integer i
# while ((1)); do
# 	for ((i=0; i<4; i++)); do
# 		if ; then
# 			notify-send "Cpu $i: usage: $use[$i], temp: $temp[$i]"
# 		fi
# 	doone
# 	sleep 2
# done
