#!/bin/zsh

#echo 2400000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
#echo 2400000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
#echo 2400000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
#echo 2400000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

for f in /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor; do
	echo powersave > $f
done

 watch grep \"cpu MHz\" /proc/cpuinfo
# integer i
# while ((1)); do
# 	for ((i=0; i<4; i++)); do
# 		if ; then
# 			notify-send "Cpu $i: usage: $use[$i], temp: $temp[$i]"
# 		fi
# 	doone
# 	sleep 2
# done
