#!/bin/zsh
for file in "$@"; do
	for paragraph in "${(f)$(cat $file | grep -v "^-$")}"; do
		echo $paragraph
		result=$(syllabecount.py $paragraph)
		echo $result
	done
done

#result=$(syllabecount.py $@)
#echo $result

#count=0
#words=
#for word in "${(@f)result}"; do
#	echo "word=$word"
#	e=(${(s.-.)word})
#	echo "count=${#e}"
#	((count+=${#e}))
#done
#echo "total=$count"

