#!/bin/zsh

# Added 2019-04-16 11:50



# Added 2019-04-16 11:51



# Added 2019-04-16 11:54
	or p in $(pidof $1); do ls -ld /proc/$p/cwd; done | awk -F'-> ' '{print $2}' | uniq


# Added 2019-04-16 14:21
	or p in $(pidof $1); do ls -ld /proc/$p/cwd; done | awk -F'-> ' '{print $2}' | uniq


# Added 2019-04-16 15:16
	or p in $(pidof $1); do ls -ld /proc/$p/cwd; done | awk -F'-> ' '{print $2}' | uniq

